//! Capabilities and their rights.
//!
//! A capability is an unforgeable token that grants authority over
//! an object. It is identified by a `CapabilityId`, which is a slot
//! index and a generation counter, and it carries:
//!
//! - a reference to the object it names
//! - the rights the holder has over that object
//!
//! To use a capability, the holder presents its `CapabilityId` to
//! the fabric. The fabric looks the ID up in the ITable, checks
//! that the generation matches, and confirms that the requested
//! rights are contained in the capability's rights.
//!
//! # Rights
//!
//! Rights are a bitmask. Which rights are meaningful depends on the
//! kind of object the capability names. The fabric enforces this:
//! a capability with `EXECUTE` on a cell is rejected, because
//! `EXECUTE` has no meaning for a cell.
//!
//! # Delegation
//!
//! A capability with `SHARE` can be used to produce a new
//! capability with the same object and a subset of rights. This is
//! the only way new capabilities come into existence. Rights are
//! therefore monotonically non-increasing along any chain of
//! delegations, which is the invariant that makes revocation
//! tractable and attenuation automatic.
//!
//! # Attenuation
//!
//! Delegation can only shrink the rights of a capability, never
//! grow them. A capability with `READ | SHARE` can produce a
//! capability with `READ`, but not one with `WRITE`. This is
//! enforced in `CapabilityCore::transfer` by the containment check
//! and is the reason the fabric never needs to consult the object
//! to decide whether a delegation is legal.
//!
//! # Mapping rights to object kinds
//!
//! Rights are a single flat bitmask, but not every bit is
//! meaningful for every object kind. The fabric is the arbiter:
//! `CapabilityCore::allocate_memory` will reject a `MemoryObject`
//! capability that carries `ENTER`, because `ENTER` has meaning
//! only for a cell. The bitmask is the encoding; the fabric is the
//! policy.

use crate::capability::object::ObjectId;

/// Identifies a capability slot.
///
/// A capability ID is a slot index combined with a generation
/// counter. The generation is incremented every time the slot is
/// reused, so a stale ID from before a reuse is rejected even
/// though it names the same slot.
///
/// # Layout
///
/// ```text
///   bits 31-16   generation
///   bits 15-0    slot index
/// ```
///
/// The split allows the generation to catch reuse without
/// requiring a separate hash table: the slot index is still the
/// primary key, and the generation is a guard.
///
/// # Why generation is in the high bits
///
/// Slot index is in the low 16 bits so that `CapabilityId::index()`
/// can be a simple mask. Generation is in the high bits. This
/// matches the ITable's internal use of the index as an array
/// offset and keeps `raw()` readable as `<generation>:<index>` in
/// hexadecimal dumps.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct CapabilityId(u32);

impl CapabilityId {
    /// The reserved invalid capability ID.
    ///
    /// Generated by `CapabilityId::new(0, 0)`. The ITable reserves
    /// slot 0 so that a zeroed capability cannot be mistaken for a
    /// valid one.
    pub const INVALID: Self = Self(0);

    /// Creates a capability ID from a slot index and a generation.
    pub const fn new(index: u16, generation: u16) -> Self {
        Self(((generation as u32) << 16) | index as u32)
    }

    /// Returns the slot index.
    pub const fn index(self) -> usize {
        (self.0 & 0xffff) as usize
    }

    /// Returns the generation.
    pub const fn generation(self) -> u16 {
        (self.0 >> 16) as u16
    }

    /// Returns the raw numeric value of the ID.
    ///
    /// Used for logging and for the ITable's internal bookkeeping.
    pub const fn raw(self) -> u32 {
        self.0
    }
}

/// The rights a capability carries.
///
/// A bitmask. Which bits are meaningful depends on the kind of
/// object the capability names.
///
/// # Memory objects
///
/// - `MAP`       install this object's frames into an address space
/// - `READ`      read the object's contents
/// - `WRITE`     modify the object's contents
/// - `EXECUTE`   use the object's frames as instruction memory
/// - `SHARE`     derive a new capability to the same object
/// - `DESTROY`   destroy the object, freeing its frames
///
/// # Address spaces
///
/// - `MAP`       install a mapping
/// - `UNMAP`     remove a mapping
/// - `ACTIVATE`  load the address space into CR3
/// - `SHARE`     derive a new capability
/// - `DESTROY`   destroy the address space
///
/// # Cells
///
/// - `ENTER`     transition execution into this cell
/// - `GRANT`     add a capability to the cell's capability space
/// - `REVOKE`    remove a capability from the cell
/// - `SHARE`     derive a new capability
/// - `DESTROY`   terminate the cell
/// 
///  # Channels
///
/// - `SEND`      place a message on the channel
/// - `RECV`      take a message off the channel
/// - `SHARE`     derive a new capability
/// - `DESTROY`   destroy the channel
///
/// The fabric rejects a capability whose rights are not all
/// meaningful for the object's kind.
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct CapabilityRights(u32);

impl CapabilityRights {
    // ---- Rights meaningful for multiple kinds. ----

    /// Authority to make the object's contents available in a
    /// virtual address space.
    ///
    /// For a memory object, this is the right to map its frames
    /// into an address space. For an address space, it is the
    /// right to install a mapping into it.
    pub const MAP: Self = Self(1 << 0);

    /// Authority to read the object's contents.
    ///
    /// For a memory object, this is the right to load its bytes.
    /// For other kinds, the meaning is defined by that kind's
    /// semantics.
    pub const READ: Self = Self(1 << 1);

    /// Authority to modify the object's contents.
    pub const WRITE: Self = Self(1 << 2);

    /// Authority to use the object's contents as instructions.
    ///
    /// For a memory object, this is the right to execute its
    /// frames. For other kinds, the meaning is defined by that
    /// kind's semantics.
    pub const EXECUTE: Self = Self(1 << 3);

    /// Authority to derive a new capability to the same object
    /// with a subset of rights.
    ///
    /// Without this right, a capability cannot be delegated. This
    /// is the mechanism by which the fabric prevents uncontrolled
    /// proliferation of authority.
    pub const SHARE: Self = Self(1 << 4);

    /// Authority to destroy the object.
    ///
    /// Destroying an object revokes every capability to it. This
    /// right is the only way to release a memory object's frames
    /// or terminate a cell.
    pub const DESTROY: Self = Self(1 << 5);

    // ---- Rights meaningful for address spaces. ----

    /// Authority to remove a mapping from an address space.
    pub const UNMAP: Self = Self(1 << 6);

    /// Authority to load an address space into CR3.
    ///
    /// Loading CR3 switches the CPU to a different address space.
    /// Only code that has been carefully audited should hold this
    /// right, because a switch to an address space that does not
    /// map the current kernel stack will fault immediately.
    pub const ACTIVATE: Self = Self(1 << 7);

    // ---- Rights meaningful for cells. ----

    /// Authority to transition execution into a cell.
    ///
    /// Holding `ENTER` over a cell is the authority to run it.
    /// This right should be held exclusively: two cells running
    /// the same execution context concurrently is a race.
    pub const ENTER: Self = Self(1 << 8);

    /// Authority to add a capability to a cell's capability space.
    pub const GRANT: Self = Self(1 << 9);

    /// Authority to remove a capability from a cell.
    pub const REVOKE: Self = Self(1 << 10);

    // ---- Rights meaningful for channels. ----

    /// Authority to place a message on a channel.
    ///
    /// A capability with `SEND` may be used as the first argument
    /// to [`CapabilityCore::send_capability`] and
    /// [`CapabilityCore::borrow_capability`]. It does not imply
    /// `RECV`: a cell can be allowed to write to a channel without
    /// being allowed to read from it, which is the natural
    /// arrangement for a request-only endpoint.
    ///
    /// [`CapabilityCore::send_capability`]:
    ///     crate::capability::core::CapabilityCore::send_capability
    /// [`CapabilityCore::borrow_capability`]:
    ///     crate::capability::core::CapabilityCore::borrow_capability
    pub const SEND: Self = Self(1 << 11);

    /// Authority to take a message off a channel.
    ///
    /// A capability with `RECV` may be used as the argument to
    /// [`CapabilityCore::recv_message`]. It does not imply `SEND`:
    /// a cell can be allowed to read from a channel without being
    /// allowed to write to it, which is the natural arrangement
    /// for a response-only endpoint.
    ///
    /// [`CapabilityCore::recv_message`]:
    ///     crate::capability::core::CapabilityCore::recv_message
    pub const RECV: Self = Self(1 << 12);

    /// Returns a rights value with no bits set.
    pub const fn empty() -> Self {
        Self(0)
    }

    /// Returns whether every bit set in `other` is also set in
    /// `self`.
    ///
    /// This is the check the fabric uses to enforce attenuation:
    /// a derived capability's rights must be contained in the
    /// parent's.
    ///
    /// # Example
    ///
    /// `(READ | WRITE).contains(READ)` is `true`.
    /// `(READ).contains(READ | WRITE)` is `false`.
    pub const fn contains(self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }

    /// Returns the intersection of two rights values.
    ///
    /// Used when a derived capability should carry the smaller of
    /// two rights sets. The `contains` check is usually used
    /// instead; `intersect` is provided for cases where the caller
    /// wants to deliberately attenuate without checking.
    pub const fn intersect(self, other: Self) -> Self {
        Self(self.0 & other.0)
    }

    /// Returns the raw bit representation.
    ///
    /// Used for logging and for the fabric's internal bookkeeping.
    pub const fn bits(self) -> u32 {
        self.0
    }
}

impl core::ops::BitOr for CapabilityRights {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self {
        Self(self.0 | rhs.0)
    }
}

impl core::ops::BitAnd for CapabilityRights {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self {
        Self(self.0 & rhs.0)
    }
}

impl core::ops::BitOrAssign for CapabilityRights {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

/// A capability: a reference to an object, with rights.
///
/// Capabilities are created by the fabric and never by callers.
/// The `CapabilityId` returned to the caller is the token; the
/// `Capability` itself lives in the ITable and is not exposed.
#[repr(C)]
pub struct Capability {
    /// The capability's own ID.
    ///
    /// Stored redundantly so that a capability can be looked up
    /// from the slot and the generation reconstructed without an
    /// external lookup.
    id: CapabilityId,

    /// The object this capability names.
    object: ObjectId,

    /// The rights this capability carries over the object.
    rights: CapabilityRights,
}

impl Capability {
    /// Creates a capability.
    pub const fn new(id: CapabilityId, object: ObjectId, rights: CapabilityRights) -> Self {
        Self { id, object, rights }
    }

    /// Returns the capability's own ID.
    pub const fn id(&self) -> CapabilityId {
        self.id
    }

    /// Returns the object this capability names.
    pub const fn object(&self) -> ObjectId {
        self.object
    }

    /// Returns the rights this capability carries.
    pub const fn rights(&self) -> CapabilityRights {
        self.rights
    }
}
